package com.capp.app;

import org.libsdl.app.SDLActivity;
import android.os.Bundle;

public class MainActivity extends SDLActivity {

    /* SDLActivity's own loadLibraries() (called from its onCreate) is what
     * actually loads the native library before invoking SDL_main - the
     * default {"SDL2", "main"} doesn't match our CMake target name, so
     * without this override it looks for a nonexistent libmain.so. */
    @Override
    protected String[] getLibraries() {
        return new String[] { "SDL2", "capp_native" };
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // Copy app.lua and assets/fonts/ (generated by the syncToolkitApp
        // Gradle task) into the writable files dir for SDL_main and
        // sdl.get_asset_path() to find. Copies raw bytes, not through a
        // Java String, so binary assets (fonts) survive intact. Scoped to
        // just these paths rather than the whole assets/ tree, which also
        // contains unrelated framework assets merged in from dependencies.
        try {
            copyAssetFile("app.lua", new java.io.File(getFilesDir(), "app.lua"));
            java.io.File assetsDir = new java.io.File(getFilesDir(), "assets");
            java.io.File fontsDir = new java.io.File(assetsDir, "fonts");
            fontsDir.mkdirs();
            copyAssetTree("fonts", fontsDir);
        } catch (Exception e) {
            android.util.Log.e("capp", "Failed to copy assets: " + e.getMessage());
        }

        super.onCreate(savedInstanceState);
    }

    /* Only ever called with a path already known to be a directory (see the
     * grandchildren check below), so entries is never a leaf file itself. */
    private void copyAssetTree(String assetPath, java.io.File destDir) throws java.io.IOException {
        String[] entries = getAssets().list(assetPath);
        for (String entry : entries) {
            String childAssetPath = assetPath.isEmpty() ? entry : assetPath + "/" + entry;
            String[] grandchildren = getAssets().list(childAssetPath);
            if (grandchildren != null && grandchildren.length > 0) {
                java.io.File childDestDir = new java.io.File(destDir, entry);
                childDestDir.mkdirs();
                copyAssetTree(childAssetPath, childDestDir);
            } else {
                copyAssetFile(childAssetPath, new java.io.File(destDir, entry));
            }
        }
    }

    private void copyAssetFile(String assetPath, java.io.File destFile) throws java.io.IOException {
        try (java.io.InputStream is = getAssets().open(assetPath);
             java.io.FileOutputStream os = new java.io.FileOutputStream(destFile)) {
            byte[] buffer = new byte[8192];
            int read;
            while ((read = is.read(buffer)) != -1) {
                os.write(buffer, 0, read);
            }
        }
        android.util.Log.i("capp", "Copied asset " + assetPath + " to " + destFile.getAbsolutePath());
    }
}
